FROM ubuntu:22.04 as builder

RUN apt-get update -y && apt-get install -y curl build-essential cmake m4 automake peg libtool autoconf python3 python3-pip git lcov openssl libssl-dev

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# add rust to path
ENV PATH="/root/.cargo/bin:${PATH}"
