FROM debian:bookworm-slim as runtime

RUN apt-get update -y && apt-get install -y build-essential cmake m4 automake peg libtool autoconf python3 python3-pip git peg lcov openssl libssl-dev curl && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
# add rust to path