FROM ubuntu:22.04 as builder

RUN apt-get update -y && apt-get install -y git wget build-essential lcov openssl libssl-dev python3 python3-venv python3-dev unzip rsync curl m4 automake peg libtool autoconf python3-pip cmake

# install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# add rust to path
ENV PATH="/root/.cargo/bin:${PATH}"
