name:  Build image

on:
  push:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - debian
          - rhel
          - rhel8
          - rhel9
          - amazonlinux2023
          - alpine

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Login to Docker Hub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Docker tags
        id: meta
        run: |
          TAGS="falkordb/falkordb-build:${{ matrix.os }}"
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            TAGS="${TAGS},falkordb/falkordb-build:${{ matrix.os }}-edge"
          elif [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            TAG_VERSION="${{ github.ref_name }}"
            # Strip 'v' prefix if present
            TAG_VERSION="${TAG_VERSION#v}"
            TAGS="${TAGS},falkordb/falkordb-build:${{ matrix.os }}-${TAG_VERSION}"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build ${{ github.ref_name == 'main' && 'and push' || ''}} image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v5
        with:
          context: .
          file: Dockerfile.${{ matrix.os }}
          cache-from: |
            type=gha,scope=${{ matrix.os }}-${{ github.ref_name }}
            type=gha,scope=${{ matrix.os }}-main
          cache-to: type=gha,mode=max,scope=${{ matrix.os }}-${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref_name == 'main' || startsWith(github.ref, 'refs/tags/') }}
          tags: ${{ steps.meta.outputs.tags }}
