name: Build sanitizer image

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Build image"]
        types:
            - completed

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push sanitizer image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Dockerfile.sanitizer
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
                  platforms: linux/amd64
                  push: true
                  tags: falkordb/falkordb-sanitizer